get_filename_component(DESTINATION ${PYTHON_CEXTENSION} DIRECTORY)

list(APPEND IGNORE_DLL_LIST kernelbase.dll)
list(APPEND IGNORE_DLL_LIST kernel32.dll)
list(APPEND IGNORE_DLL_LIST ${DIRECTORY}/vcruntime140.dll)
list(JOIN IGNORE_DLL_LIST "|" POST_EXCLUDE_REGEXES)

file(GET_RUNTIME_DEPENDENCIES
    LIBRARIES ${PYTHON_CEXTENSION}
    RESOLVED_DEPENDENCIES_VAR deps
    UNRESOLVED_DEPENDENCIES_VAR ds
    DIRECTORIES ${DIRECTORIES}
    POST_EXCLUDE_REGEXES "${POST_EXCLUDE_REGEXES}"
    )


file(INSTALL ${deps} DESTINATION ${DESTINATION})
