get_filename_component(DESTINATION ${PYTHON_CEXTENSION} DIRECTORY)
file(GET_RUNTIME_DEPENDENCIES
    LIBRARIES ${PYTHON_CEXTENSION}
    RESOLVED_DEPENDENCIES_VAR deps
    UNRESOLVED_DEPENDENCIES_VAR ds
    DIRECTORIES ${DIRECTORIES}
    POST_EXCLUDE_REGEXES "kernelbase.dll|kernel32.dll"
    )


file(INSTALL ${deps} DESTINATION ${DESTINATION})
